version: '3.6'

services:
  weather-tp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ./:/project/app
    command: |
      bash -c "
        weather-tp -vv -C tcp://validator:4004
      "
    stop_signal: SIGKILL